name: Give Strava Kudos

on:
  schedule:
    - cron: "10 5-23/6 * * *"
  workflow_dispatch:

env:
  STRAVA_EMAIL: ${{ secrets.STRAVA_EMAIL }}
  STRAVA_PASSWORD: ${{ secrets.STRAVA_PASSWORD }}
jobs:
  run-kudos-cron:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3 
      - uses: actions/setup-python@v4
        with:
          python-version-file: 'python-3.14.0-beta.2-linux-22.04-x64.tar.gz'
          cache: 'pip'
      - run: pip install -r requirements.txt
      - run: playwright install
      - run: python give_kudos.py
        
